which.profile=@which.profile@

spring.application.name=payBridge

#-----------------------------------------------------------
# app directories  ----------------------------
#-----------------------------------------------------------
baseDir=@baseDir@
logsBaseDir=@logsBaseDir@


momo.third-party-id=@momo.third-party-id@
momo.password=@momo.password@
momo.result-url=@momo.result-url@
momo.key-owner=@momo.key-owner@
momo.channel-code=@momo.channel-code@

momo.base-url=@momo.base-url@
momo.payment-endpoint=@momo.payment-endpoint@
momo.sync-endpoint=@momo.sync-endpoint@
